помощь друга
htmlacademy-javascript/2558253-kekstagram-2 pull request #11
Opened 2024-12-05 01:41 UTC by bator-batuev

1. добавлен функционал изменения масштаба превью 
2. реализован функционал применения эффектов к изображению с помощью библиотеки noUiSlider

2024-12-05 17:36 UTC, fyvfyv requested changes

2024-12-06 02:13 UTC, bator-batuev commented on .editorconfig
> +insert_final_newline = false
Да, я заканчиваю всегда пустой строкой. Просто очень бесит, когда редактор не дает дописать строчку и постоянно прыгает вниз.

2024-12-06 02:17 UTC, bator-batuev commented on js/effects-slider.js
> +    }
использовал метод find, получил ошибку, что find с nodelist не работает, перевел в массив с помощью array.from.

2024-12-06 10:29 UTC, fyvfyv commented on js/effects-slider.js
> +import {getEffectSelector, styleFilterByEffects, Effects} from './const.js';
Нет, ошибка говорит, что у тебя отсутствует noUiSlider. Если посмотреть в консоль, то там видно, что не загрузилось много ресурсов. 

<img width="1195" alt="Screenshot 2024-12-06 at 10 27 50 AM" src="https://github.com/user-attachments/assets/cfd25afc-323b-4024-a9db-05ef51c021e8">

А это всё потому что у тебя абсолютные пути `/vendor/...`. А при сборке на гитхабе у нас URL меняется, например, вот https://htmlacademy-javascript.github.io/2558253-kekstagram-2/11/
И получается что у тебя эти файлы ищутся не в `/2558253-kekstagram-2/11/vendor/...` а просто в `/vendor`. Где, конечно, ничего нет. 
А локально у тебя работает, потому что у тебя проект запускается на 127.0.0.1/ и там совпадают пути

2024-12-06 14:22 UTC, merged