Добавлен сценарий просмотра фотографий в полноэкранном режиме
htmlacademy-javascript/2558253-kekstagram-2 pull request #7
Opened 2024-11-13 00:54 UTC by bator-batuev

2024-11-13 21:15 UTC, fyvfyv requested changes
Твой код содержит довольно много комментариев, и это может считаться антипаттерном — когда избыточные пояснения делают код перегруженным и сложным для восприятия. Комментарии, объясняющие очевидные вещи, часто увеличивают объем кода, не добавляя реальной ценности.

Считается хорошей практикой писать самодокументируемый код, то есть выбирать такие имена переменных и функций, чтобы их смысл был ясен без дополнительных пояснений. Обычно комментарии оставляют только там, где логика сложная или требует объяснения, которое невозможно выразить через имена.

Если тебе сейчас так удобнее, и комментарии помогают ориентироваться, можешь оставить их. Со временем, когда почувствуешь себя увереннее, попробуй минимизировать комментарии, сохраняя только те, которые добавляют что-то действительно полезное к пониманию кода.

---

Ещё у тебя в файле `js/functions.js` остались console.log, на которые ругается ESLint, давай их уберем, чтобы не мешались

2024-11-13 21:15 UTC, fyvfyv commented on js/img-view.js
> +});
Ты импортируешь pictureBlock здесь только для того, чтобы навесить обработчик, но сам элемент определяется в другом месте. В итоге, логика «подготовки» этого блока оказывается размазанной по двум файлам, что делает ее неочевидной. Лучше сделать рефакторинг так, чтобы код был более «цельным»: каждый блок логики завершённым, без необходимости переходить между файлами для понимания, где какая часть инициализируется.

2024-11-14 04:58 UTC, bator-batuev commented on js/img-view.js
> +});
Перенести этот фрагмент в thumbnails.js?

2024-11-14 10:15 UTC, fyvfyv commented on js/img-view.js
> +});
Да, например, и тогда img-view хорошо переименовать в что-то про big-picture (т.к. он только им и будет заниматься).
Кстати, тебе возможно будет проще, если просто на бумаге попробуешь нарисовать связи. Просто каждый файлик - это квадрат, а стрелочками туда-обратно между ними импорты/экспорты. И потом попробовать посмотреть, где можно упростить связи.

2024-11-14 10:15 UTC, fyvfyv commented on js/img-view.js
> +  bigPictureCancelNode.removeEventListener('click', onBigPictureCancelClick);
Ты можешь изменить здесь стрелочные функции на `function declaration`, т.е. `function closeBigPicture` и т. д. Тогда благодаря [хоистингу](https://developer.mozilla.org/en-US/docs/Glossary/Hoisting) эта ошибка исчезнет

2024-11-14 23:20 UTC, fyvfyv requested changes

2024-11-14 23:20 UTC, fyvfyv commented on js/open-big-picture.js
> +function openBigPicture (pictureId) {
Смотир, при проверке тоже указало на ошибку. У тебя функция объявлена, но не экспортируется (хотя ты её используешь рядом)

2024-11-15 00:00 UTC, bator-batuev commented on js/open-big-picture.js
> +function openBigPicture (pictureId) {
Точно, забыл про экспорт. Думал, ошибка указывает, что функция не используется конкретно в этом модуле.

2024-11-16 16:17 UTC, merged